export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Me',
    headline: 'Á eftir að ákveða',
    description: 'Á eftir að ákveða',
    buttonLabel: 'Kannski, kannski ekki ?',
    imgStart: false,
    img: '/images/profile.jpg',
    alt: 'ProfilePic',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Cock and balls torture',
    headline: 'Á eftir að ákveða',
    description: 'Á eftir að ákveða',
    buttonLabel: 'Kannski, kannski ekki ?',
    imgStart: false,
    img: '/images/profile.jpg',
    alt: 'ProfilePic',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjThree = {
    id: 'game',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Snake',
    headline: 'Play a simple snake game!',
    description: 'Use the arrows to move the snake and try to catch as many fruits as you can!',
    dark: true,
    primary: true,
    darkText: false,
};
export const homeObjFour = {
    id: 'questions',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Here you can access the code for my website.',
    headline: 'Á eftir að ákveða',
    description: 'Á eftir að ákveða',
    dark: true,
    primary: true,
    darkText: false,
};
/*export const homeObjFour = {
    id: 'signin',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Simple snake game',
    headline: 'Play a game!',
    description: 'Á eftir að ákveða',
    buttonLabel: 'Kannski, kannski ekki ?',
    imgStart: false,
    img: '/images/profile.jpg',
    alt: 'ProfilePic',
    dark: true,
    primary: true,
    darkText: false,
};*/