export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightTopText: true, 
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Me',
    headline: 'Á eftir að ákveða',
    description: 'Á eftir að ákveða',
    buttonLabel: 'Kannski, kannski ekki ?',
    imgStart: false,
    img: '/images/profile.jpg',
    alt: 'ProfilePic',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'resume',
    lightBg: true,
    lightTopText: false, 
    lightText: false,
    lightTextDesc: false,
    topLine: 'My not so impressive resume',
    headline: 'Á eftir að ákveða',
    description: 'Á eftir að ákveða',
    buttonLabel: 'Kannski, kannski ekki ?',
    imgStart: false,
    img: '/images/profile.jpg',
    alt: 'ProfilePic',
    dark: true,
    primary: true,
    darkText: true,
};

export const homeObjThree = {
    id: 'game',
    lightBg: false,
    lightTopText: true, 
    lightText: true,
    lightTextDesc: true,
    topLine: 'Snake',
    headline: 'Play a simple snake game!',
    description: 'Use the arrows to move the snake and try to catch as many fruits as you can!',
    dark: true,
    primary: true,
    darkText: false,
};
export const homeObjFour = {
    id: 'questions',
    lightBg: true,
    lightTopText: false, 
    lightText: false,
    lightTextDesc: false,
    topLine: 'Question time!',
    headline: 'Questions',
    description: 'Answer these four questions if you like.',
    dark: true,
    primary: true,
    darkText: true,
};
/*export const homeObjFour = {
    id: 'signin',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Simple snake game',
    headline: 'Play a game!',
    description: 'Á eftir að ákveða',
    buttonLabel: 'Kannski, kannski ekki ?',
    imgStart: false,
    img: '/images/profile.jpg',
    alt: 'ProfilePic',
    dark: true,
    primary: true,
    darkText: false,
};*/